,
  'ABG test', 'acidemia',
  'ACLS',
  'acute',
  'Acute respiratory failure',
  'adynamia',
  'agitation',
  'airway management',
  'amnesia',
  'Angiogram',
  'anoxia',
  'anoxic brain injury',
  'arrythmia',
  asystole,
  basic life support,
  blood gas test,
  BLS,
  brain dead,
  brain death,
  brain death evaluation,
  brain imaging,
  brain injury,
  bystander CPR,
  cardiac,
  Cardiac Arrest,
  cardiac enzymes,
  cardiac ROS,
  cardiomyopathy,
  cerebral hypoperfusion,
  cerebral hypoxia,
  chest compressions,
  Chest Pain,
  Chest x-ray,
  coma,
  commotio cordis,
  communication disorders,
  computed tomography scan,
  coronary artery disease,
  CPR,
  Critical care,
  CT,
  CTA,
  defibrillation,
  diagnosis,
  disability assessment,
  dizziness,
  drug use,
  duration of resuscitation,
  dysphagia,
  echo,
  echocardiogram,
  EKG,
  family discussion,
  fatigue,
  functional recovery,
  GCS,
  heart,
  heart defect,
  Heart Disease,
  Heart Palpitations,
  hemodynamic instability,
  hemodynamic monitoring,
  hemodynamics,
  High BP,
  High cholesterol,
  History of Heart Disease,
  hypokinesia,
  hypoxia,
  hypoxic,
  ICU,
  impaired attention,
  Insufficient CBF,
  intubation,
  involuntary movements,
  irregular electrical activity,
  ischemia,
  IV,
  LOC,
  loss of consciousness,
  mechanical ventilation,
  memory disorder,
  MRI,
  Nausea,
  Neurological consultation,
  neurological deficits,
  Neurological impairment,
  Neurological impairment,
  Neurology,
  neuropathology,
  nuclear scan,
  nutritional deficiency,
  obesity,
  oxygenation,
  PE,
  PEA,
  Pulseless Electrical Activity,
  PVS,
  Permanent Vegetative State,
  quadriparesis,
  quality of life,
  quality of life assessment,
  Reactive Oxygen Species,
  reduced verbal fluency,
  rehabilitation,
  Respiratory failure,
  resuscitation,
  return of spontanteous circulation,
  rigidity,
  ROSC,
  smoking,
  SOB,
  sudden,
  time of arrest,
  trauma,
  unawareness,
  unresponsiveness,
  valvular heart disease,
  Ventricular Fibrillation,
  Vfib